# ============================================================================
# 帮助信息 (mk/help.mk)
# ============================================================================

.PHONY: help
help:
	@echo "📖 可用的 Make 命令 (规则拆分至 mk/ 目录)"
	@echo ""
	@echo "  📄 Document Parser (mk/document-parser.mk):"
	@echo "    make build-document-parser          - 双架构 (amd64+arm64，默认)"
	@echo "    make build-document-parser-x86_64   - 仅 x86_64"
	@echo "    make build-document-parser-arm64    - 仅 ARM64"
	@echo ""
	@echo "  🎤 Voice CLI (mk/voice-cli.mk):"
	@echo "    make build-voice-cli               - 双架构 (默认)"
	@echo "    make build-voice-cli-x86_64        - 仅 x86_64 (CPU 后端)"
	@echo "    make build-voice-cli-arm64         - 仅 ARM64"
	@echo "    (GPU cuda: 见 mk/voice-cli.mk 顶部 --build-arg 说明)"
	@echo ""
	@echo "  🔎 FastEmbed (mk/fastembed.mk) [开发中]:"
	@echo "    make build-fastembed               - 双架构 (默认)"
	@echo "    make build-fastembed-x86_64        - 仅 x86_64"
	@echo "    make build-fastembed-arm64         - 仅 ARM64"
	@echo ""
	@echo "  🔌 MCP Proxy (mk/mcp-proxy.mk):"
	@echo "    make build-mcp-proxy               - 当前架构 (context=..，历史写法)"
	@echo ""
	@echo "  📦 全局构建 (mk/all.mk):"
	@echo "    make build-all-x86_64              - 三模块 x86_64"
	@echo "    make build-all-arm64               - 三模块 ARM64"
	@echo "    make build-all-multi               - 三模块双架构"
	@echo ""
	@echo "  🐳 Docker 镜像/运行 (mk/docker.mk):"
	@echo "    make build-image                   - mcp-proxy 运行镜像"
	@echo "    make build-image-document-parser   - document-parser 运行镜像"
	@echo "    make run / run-fg                  - docker-compose 启动 mcp-proxy"
	@echo "    make run-document-parser           - 运行 document-parser 容器"
	@echo "    make check-buildx / setup-buildx   - buildx 检查/设置"
	@echo ""
	@echo "  📦 MCP 发布 (mk/publish.mk):"
	@echo "    make mcp-version-show              - 查看版本号"
	@echo "    make mcp-version-update            - 版本号 +1"
	@echo "    make mcp-publish                   - 发布到 crates.io (按依赖顺序)"
	@echo "    make mcp-publish-dry-run           - 预览发布 (不实际发布)"
	@echo "    make mcp-package-list              - 查看各包文件列表"
	@echo ""
	@echo "  🧹 清理 (mk/clean.mk):"
	@echo "    make clean                         - 清理 ./dist/"
	@echo "    make clean-images                  - 清理 Docker 镜像/缓存"
	@echo ""
	@echo "  ❓ make help                         - 显示此帮助"
	@echo ""
	@echo "📊 输出目录: ./dist/<module>-{x86_64,arm64}/  (双架构各自独立目录)"
	@echo ""
	@echo "💡 双架构说明: 无后缀目标 (build-<name>) 串行构建 x86_64 + arm64 两次。"
	@echo "   --output type=local 不支持单次多平台 (二进制同名冲突)。"
