use crate::models::Config;
use crate::VoiceCliError;
use std::path::PathBuf;
use tracing::{info, warn};

pub struct ConfigManager {
    config_path: PathBuf,
    config: Config,
}

impl ConfigManager {
    pub fn new(config_path: PathBuf) -> crate::Result<Self> {
        let config = Config::load_or_create(&config_path)?;
        
        // Validate configuration
        config.validate()?;
        
        // Ensure required directories exist
        Self::ensure_directories(&config)?;
        
        Ok(Self {
            config_path,
            config,
        })
    }

    pub fn config(&self) -> &Config {
        &self.config
    }

    pub fn config_path(&self) -> &PathBuf {
        &self.config_path
    }

    pub fn reload(&mut self) -> crate::Result<()> {
        info!("Reloading configuration from {:?}", self.config_path);
        self.config = Config::load_or_create(&self.config_path)?;
        self.config.validate()?;
        Self::ensure_directories(&self.config)?;
        Ok(())
    }

    pub fn save(&self) -> crate::Result<()> {
        self.config.save(&self.config_path)?;
        info!("Configuration saved to {:?}", self.config_path);
        Ok(())
    }

    pub fn update_config<F>(&mut self, updater: F) -> crate::Result<()>
    where
        F: FnOnce(&mut Config),
    {
        updater(&mut self.config);
        self.config.validate()?;
        self.save()?;
        Ok(())
    }

    fn ensure_directories(config: &Config) -> crate::Result<()> {
        // Create models directory
        let models_dir = config.models_dir_path();
        if !models_dir.exists() {
            std::fs::create_dir_all(&models_dir)?;
            info!("Created models directory: {:?}", models_dir);
        }

        // Create logs directory
        let logs_dir = config.log_dir_path();
        if !logs_dir.exists() {
            std::fs::create_dir_all(&logs_dir)?;
            info!("Created logs directory: {:?}", logs_dir);
        }

        // Create daemon work directory if needed
        let work_dir = PathBuf::from(&config.daemon.work_dir);
        if !work_dir.exists() {
            std::fs::create_dir_all(&work_dir)?;
            info!("Created daemon work directory: {:?}", work_dir);
        }

        Ok(())
    }

    /// Generate a default configuration file with comments
    pub fn generate_default_config_with_comments(config_path: &PathBuf) -> crate::Result<()> {
        let config_yaml = r#"# Voice CLI Configuration File
# This file is automatically generated with default values

server:
  # Server binding address (0.0.0.0 for all interfaces)
  host: "0.0.0.0"
  # Server port
  port: 8080
  # Maximum file size for uploads (in bytes) - 200MB default
  max_file_size: 209715200
  # Enable CORS for web browser access
  cors_enabled: true

whisper:
  # Default model to use for transcription
  default_model: "base"
  # Directory to store whisper models
  models_dir: "./models"
  # Automatically download models when needed
  auto_download: true
  # List of supported whisper models
  supported_models:
    - "tiny"
    - "tiny.en"
    - "base"
    - "base.en"
    - "small"
    - "small.en"
    - "medium"
    - "medium.en"
    - "large-v1"
    - "large-v2"
    - "large-v3"

logging:
  # Log level (trace, debug, info, warn, error)
  level: "info"
  # Directory for log files
  log_dir: "./logs"
  # Maximum size per log file
  max_file_size: "10MB"
  # Maximum number of log files to keep
  max_files: 5

daemon:
  # PID file for daemon mode
  pid_file: "./voice-cli.pid"
  # Log file for daemon output
  log_file: "./logs/daemon.log"
  # Working directory for daemon
  work_dir: "./"
"#;

        if let Some(parent) = config_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        
        std::fs::write(config_path, config_yaml)?;
        info!("Generated default configuration file at {:?}", config_path);
        
        Ok(())
    }

    /// Validate the current environment and configuration
    pub fn validate_environment(&self) -> crate::Result<()> {
        let config = &self.config;

        // Check if models directory is writable
        let models_dir = config.models_dir_path();
        if models_dir.exists() {
            let test_file = models_dir.join(".write_test");
            match std::fs::write(&test_file, "test") {
                Ok(_) => {
                    let _ = std::fs::remove_file(test_file);
                }
                Err(_) => {
                    return Err(VoiceCliError::Config(
                        format!("Models directory is not writable: {:?}", models_dir)
                    ));
                }
            }
        }

        // Check if logs directory is writable
        let logs_dir = config.log_dir_path();
        if logs_dir.exists() {
            let test_file = logs_dir.join(".write_test");
            match std::fs::write(&test_file, "test") {
                Ok(_) => {
                    let _ = std::fs::remove_file(test_file);
                }
                Err(_) => {
                    return Err(VoiceCliError::Config(
                        format!("Logs directory is not writable: {:?}", logs_dir)
                    ));
                }
            }
        }

        // Check if port is available (basic check)
        if let Err(_) = std::net::TcpListener::bind(format!("{}:{}", config.server.host, config.server.port)) {
            warn!("Port {}:{} may not be available", config.server.host, config.server.port);
        }

        info!("Environment validation passed");
        Ok(())
    }

    /// Get configuration summary for logging
    pub fn get_summary(&self) -> String {
        format!(
            "Config Summary:\n  Server: {}:{}\n  Max file size: {} MB\n  Models dir: {}\n  Logs dir: {}\n  Default model: {}",
            self.config.server.host,
            self.config.server.port,
            self.config.server.max_file_size / 1024 / 1024,
            self.config.whisper.models_dir,
            self.config.logging.log_dir,
            self.config.whisper.default_model
        )
    }
}